# Copyright (c) 2025, Personal Robotics Laboratory
# License: BSD 3-Clause. See LICENSE.md file in root directory.

imu_publisher:
  ros__parameters:
    serial_port: "/dev/ttyUSB1"
    baud_rate: 115200
    frame_id: "imu_frame"
