version: "3.8"
services:
  articutool:
    image: ros2_articutool:latest
    network_mode: host
    privileged: true
    devices:
      - "/dev/imu:/dev/imu"
      - "/dev/u2d2:/dev/u2d2"
    volumes:
      - "/run/udev:/run/udev:ro"
      - "/etc/udev:/etc/udev:ro"
      - "/dev:/dev"
    entrypoint: ["/bin/bash"] # change the entry point.
