# Copyright (c) 2025, Personal Robotics Laboratory
# License: BSD 3-Clause. See LICENSE.md file in root directory.

imu_filter:
  ros__parameters:
    stateless: false
    use_mag: false
    publish_tf: false
    reverse_tf: false
    fixed_frame: "atool_imu_frame"
    constant_dt: 0.0
    publish_debug_topics: false
    world_frame: "enu"
    gain: 0.5
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.0
