articutool_orientation:
  ros__parameters:
    frame_id: "imu_frame" # The frame ID of the IMU
    world_frame: "world" # The world frame ID
    base_link: "af_link_base"
    tip_link: "forkTip"
    desired_pose:
      position: {x: 0.0, y: 0.0, z: 0.2}
      orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
